#!/bin/bash
# =============================================================
# Interactive notification setup for 3D-Ising-CFT-Bootstrap
# =============================================================
#
# This script guides you through configuring email and Slack
# notifications for the bootstrap pipeline.
#
# Usage:
#   bash scripts/setup_notifications.sh
#
# Output:
#   .env.notifications (in project root)
#
# =============================================================

set -e

PROJECT_DIR="/n/holylabs/schwartz_lab/Lab/obarrera/3D-Ising-CFT-Bootstrap"
cd "$PROJECT_DIR"

echo "============================================="
echo "Bootstrap Pipeline Notification Setup"
echo "============================================="
echo ""

# Detect default email
DEFAULT_EMAIL="${USER}@fas.harvard.edu"

echo "This script will configure automated notifications for:"
echo "  • Stage A completion"
echo "  • Stage A validation result (pass/fail)"
echo "  • Stage B submission"
echo "  • Stage B completion"
echo "  • Figure 6 generation"
echo "  • Progressive validation anomaly alerts"
echo ""
echo "Notifications are optional but recommended for 60-hour runs."
echo ""

# --- Email Configuration ---
echo "=== Email Notifications ==="
echo ""
read -p "Enable email notifications? (y/n) [y]: " ENABLE_EMAIL
ENABLE_EMAIL="${ENABLE_EMAIL:-y}"

if [ "$ENABLE_EMAIL" = "y" ] || [ "$ENABLE_EMAIL" = "Y" ]; then
    EMAIL_ENABLED=1
    echo ""
    read -p "Email address [$DEFAULT_EMAIL]: " EMAIL
    EMAIL="${EMAIL:-$DEFAULT_EMAIL}"
    echo "✓ Email notifications will be sent to: $EMAIL"
else
    EMAIL_ENABLED=0
    EMAIL=""
    echo "✓ Email notifications disabled"
fi

echo ""

# --- Slack Configuration ---
echo "=== Slack Notifications (Optional) ==="
echo ""
echo "To enable Slack notifications, you need a webhook URL:"
echo "  1. Visit https://api.slack.com/messaging/webhooks"
echo "  2. Click 'Create your Slack app'"
echo "  3. Enable 'Incoming Webhooks'"
echo "  4. Add webhook to your workspace"
echo "  5. Copy the webhook URL (starts with https://hooks.slack.com/...)"
echo ""

read -p "Enable Slack notifications? (y/n) [n]: " ENABLE_SLACK
ENABLE_SLACK="${ENABLE_SLACK:-n}"

if [ "$ENABLE_SLACK" = "y" ] || [ "$ENABLE_SLACK" = "Y" ]; then
    SLACK_ENABLED=1
    echo ""
    read -p "Slack webhook URL: " WEBHOOK

    if [ -z "$WEBHOOK" ]; then
        echo "⚠ Warning: No webhook URL provided. Slack disabled."
        SLACK_ENABLED=0
        WEBHOOK=""
    elif [[ ! "$WEBHOOK" =~ ^https://hooks\.slack\.com/ ]]; then
        echo "⚠ Warning: Webhook URL doesn't look valid (should start with https://hooks.slack.com/)"
        echo "   Slack notifications may not work."
    else
        echo "✓ Slack notifications configured"
    fi
else
    SLACK_ENABLED=0
    WEBHOOK=""
    echo "✓ Slack notifications disabled"
fi

echo ""

# --- Notification Filters ---
echo "=== Notification Filters ==="
echo ""
echo "You can disable specific notification types if desired."
echo "For most users, enabling all notifications is recommended."
echo ""

read -p "Customize notification types? (y/n) [n]: " CUSTOMIZE
CUSTOMIZE="${CUSTOMIZE:-n}"

if [ "$CUSTOMIZE" = "y" ] || [ "$CUSTOMIZE" = "Y" ]; then
    echo ""
    read -p "Notify on Stage A completion? (y/n) [y]: " N1
    NOTIFY_STAGE_A_COMPLETE=$( [ "${N1:-y}" = "y" ] && echo 1 || echo 0 )

    read -p "Notify on Stage A validation result? (y/n) [y]: " N2
    NOTIFY_STAGE_A_VALIDATION=$( [ "${N2:-y}" = "y" ] && echo 1 || echo 0 )

    read -p "Notify on Stage B submission? (y/n) [y]: " N3
    NOTIFY_STAGE_B_SUBMIT=$( [ "${N3:-y}" = "y" ] && echo 1 || echo 0 )

    read -p "Notify on Stage B completion? (y/n) [y]: " N4
    NOTIFY_STAGE_B_COMPLETE=$( [ "${N4:-y}" = "y" ] && echo 1 || echo 0 )

    read -p "Notify on Figure 6 generation? (y/n) [y]: " N5
    NOTIFY_FIGURE_COMPLETE=$( [ "${N5:-y}" = "y" ] && echo 1 || echo 0 )

    read -p "Notify on anomaly warnings? (y/n) [y]: " N6
    NOTIFY_ANOMALY_WARNING=$( [ "${N6:-y}" = "y" ] && echo 1 || echo 0 )

    read -p "Notify on anomaly critical alerts? (y/n) [y]: " N7
    NOTIFY_ANOMALY_CRITICAL=$( [ "${N7:-y}" = "y" ] && echo 1 || echo 0 )
else
    # Enable all by default
    NOTIFY_STAGE_A_COMPLETE=1
    NOTIFY_STAGE_A_VALIDATION=1
    NOTIFY_STAGE_B_SUBMIT=1
    NOTIFY_STAGE_B_COMPLETE=1
    NOTIFY_FIGURE_COMPLETE=1
    NOTIFY_ANOMALY_WARNING=1
    NOTIFY_ANOMALY_CRITICAL=1
    echo "✓ All notification types enabled"
fi

echo ""

# --- Write Configuration ---
echo "=== Writing Configuration ==="
echo ""

cat > .env.notifications <<EOF
# =============================================================
# Notification Configuration for 3D-Ising-CFT-Bootstrap
# =============================================================
#
# Generated by: scripts/setup_notifications.sh
# Date: $(date)
#
# This file is loaded by scripts/notification.py and SLURM
# scripts to determine notification settings.
#
# To reconfigure, run: bash scripts/setup_notifications.sh
# =============================================================

# Email Settings
EMAIL_ENABLED=$EMAIL_ENABLED
EMAIL_RECIPIENT="$EMAIL"

# Slack Settings
SLACK_ENABLED=$SLACK_ENABLED
SLACK_WEBHOOK_URL="$WEBHOOK"

# Notification Filters
# Set to 0 to disable specific notification types
NOTIFY_STAGE_A_COMPLETE=$NOTIFY_STAGE_A_COMPLETE
NOTIFY_STAGE_A_VALIDATION=$NOTIFY_STAGE_A_VALIDATION
NOTIFY_STAGE_B_SUBMIT=$NOTIFY_STAGE_B_SUBMIT
NOTIFY_STAGE_B_COMPLETE=$NOTIFY_STAGE_B_COMPLETE
NOTIFY_FIGURE_COMPLETE=$NOTIFY_FIGURE_COMPLETE
NOTIFY_ANOMALY_WARNING=$NOTIFY_ANOMALY_WARNING
NOTIFY_ANOMALY_CRITICAL=$NOTIFY_ANOMALY_CRITICAL
EOF

echo "✓ Configuration saved to: .env.notifications"
echo ""

# --- Test Notifications ---
echo "=== Testing Notifications ==="
echo ""
read -p "Send test notification now? (y/n) [y]: " TEST
TEST="${TEST:-y}"

if [ "$TEST" = "y" ] || [ "$TEST" = "Y" ]; then
    echo ""
    echo "Sending test notification..."
    echo ""

    # Source configuration
    source .env.notifications

    # Run test
    python scripts/notification.py --test

    echo ""
    echo "If you received the test notification, setup is complete!"
    echo ""
else
    echo "✓ Skipping test (you can test later with: python scripts/notification.py --test)"
    echo ""
fi

# --- Summary ---
echo "============================================="
echo "Setup Complete"
echo "============================================="
echo ""
echo "Configuration file: .env.notifications"
echo ""
echo "The pipeline will now send notifications for key events."
echo "To disable notifications, set EMAIL_ENABLED=0 and SLACK_ENABLED=0"
echo "in .env.notifications"
echo ""
echo "Next steps:"
echo "  1. Review configuration: cat .env.notifications"
echo "  2. Test notifications: python scripts/notification.py --test"
echo "  3. Run pipeline with monitoring enabled"
echo ""
